// <auto-generated />
using ELibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELibrary.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ELibrary.Models.admin.admin", b =>
                {
                    b.Property<int>("id_admin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_admin"), 1L, 1);

                    b.Property<string>("name_admin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_admin");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("ELibrary.Models.feature.baigiang", b =>
                {
                    b.Property<int>("id_bg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_bg"), 1L, 1);

                    b.Property<string>("description_bg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_bg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_bg");

                    b.ToTable("baigiang");
                });

            modelBuilder.Entity("ELibrary.Models.feature.data_file", b =>
                {
                    b.Property<int>("id_file")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_file"), 1L, 1);

                    b.Property<string>("Extension_file")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_file")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_file");

                    b.ToTable("data_file");
                });

            modelBuilder.Entity("ELibrary.Models.feature.dethikiemtra", b =>
                {
                    b.Property<int>("id_dtkt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_dtkt"), 1L, 1);

                    b.Property<string>("description_dtks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_dtkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_dtkt");

                    b.ToTable("dethikiemtra");
                });

            modelBuilder.Entity("ELibrary.Models.feature.dsmongiangday", b =>
                {
                    b.Property<int>("id_dsmgd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_dsmgd"), 1L, 1);

                    b.Property<string>("description_dsmh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_dsmgd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_dsmgd");

                    b.ToTable("dsmongiangday");
                });

            modelBuilder.Entity("ELibrary.Models.feature.help", b =>
                {
                    b.Property<int>("id_help")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_help"), 1L, 1);

                    b.Property<string>("description_help")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_help")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_help");

                    b.ToTable("help");
                });

            modelBuilder.Entity("ELibrary.Models.feature.nganhangdethi", b =>
                {
                    b.Property<int>("id_nhdt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_nhdt"), 1L, 1);

                    b.Property<string>("description_nhdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_nhdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_nhdt");

                    b.ToTable("nganhangdethi");
                });

            modelBuilder.Entity("ELibrary.Models.feature.tailieumonhoc", b =>
                {
                    b.Property<int>("id_tlmh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tlmh"), 1L, 1);

                    b.Property<string>("name_tlmh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tlmh");

                    b.ToTable("tailieumonhoc");
                });

            modelBuilder.Entity("ELibrary.Models.feature.tainguyen", b =>
                {
                    b.Property<int>("id_tn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tn"), 1L, 1);

                    b.Property<string>("description_tn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_tn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tn");

                    b.ToTable("tainguyen");
                });

            modelBuilder.Entity("ELibrary.Models.feature.thongbao", b =>
                {
                    b.Property<int>("id_tb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tb"), 1L, 1);

                    b.Property<string>("description_tb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_tb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tb");

                    b.ToTable("thongbao");
                });

            modelBuilder.Entity("ELibrary.Models.teacher.teacher", b =>
                {
                    b.Property<int>("id_teacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_teacher"), 1L, 1);

                    b.Property<string>("name_teacher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_teacher");

                    b.ToTable("teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
